### ISSUE TITLE
New Installation not working

### ISSUE THREAD

**Issue by adgower** [worksome/envy#14]
Laravel new project

install package

modify .env - (add api configs, secrets, etc)

php artisan envy:install

php artisan envy:sync

"There are no variables to sync!"

**Comment by olivernybroe** [comment]
Hi, I might be misunderstanding you are doing, but here is my assumption.

You are adding env variables to your .env file and running the sync command, expecting it to notify you about env variables missing in your `.env.example` file which are present in your `.env` file.

However this is not what this library does. This library makes sure all your env variables used in your config files are present in your `.env.example` file. 

I'll close this issue, however if my assumption is wrong, then please correct me and I'll reopen the issue, so we can investigate further what happens for you.
