### ISSUE TITLE
Laravel support version needs to be increased

### ISSUE THREAD

**Issue by a-bashtannik** [worksome/envy#15]
See

https://github.com/worksome/envy/blob/6722ca6604e3b8564d0ffed7139144e05bde88c2/src/Commands/SyncCommand.php#L69 uses `Blade::render` method, which was introduced in Laravel v8.80 (See https://github.com/laravel/framework/pull/40425) 

https://github.com/worksome/envy/blob/6722ca6604e3b8564d0ffed7139144e05bde88c2/composer.json#L20

Trying to use the package on Laravel <8.80 will cause error:

```
  Call to undefined method Illuminate\View\Compilers\BladeCompiler::render()
```

Need to set min. requirement to 8.80 in composer.json

**Comment by olivernybroe** [comment]
Thanks for reporting this and with such a detailed report! 

Would you like to submit a PR for it?

**Comment by olivernybroe** [comment]
Thank you! 🤩
