### ISSUE TITLE
not compatible with php 7.4

### ISSUE THREAD

**Issue by havasjeancarlostrabajo** [worksome/envy#25]
[InvalidArgumentException]
  Package worksome/envy has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

![image](https://user-images.githubusercontent.com/96260366/172741083-3e7ce951-3982-44ac-893d-ec862a0cc91b.png)

**Comment by olivernybroe** [comment]
Yes. we do not support 7.4 and do not plan on it, this is not a mistake 👍
