### ISSUE TITLE
Fails if no .env.example exists to begin with

### ISSUE THREAD

**Issue by AJenbo** [worksome/envy#8]
```
   ErrorException 

  file_get_contents(/Users/ajenbo/monorepo/projects/backoffice/backoffice-website/.env.example): Failed to open stream: No such file or directory

  at vendor/thecodingmachine/safe/generated/filesystem.php:319
    315▕         $result = \file_get_contents($filename, $use_include_path, $context, $offset);
    316▕     } elseif ($context !== null) {
    317▕         $result = \file_get_contents($filename, $use_include_path, $context);
    318▕     } else {
  ➜ 319▕         $result = \file_get_contents($filename, $use_include_path);
    320▕     }
    321▕     if ($result === false) {
    322▕         throw FilesystemException::createFromPhpError();
    323▕     }

      +4 vendor frames 
  5   [internal]:0
      Worksome\Envy\Envy::Worksome\Envy\{closure}("/Users/ajenbo/monorepo/projects/backoffice/backoffice-website/.env.example")

      +16 vendor frames 
  22  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by lukeraymonddowning** [comment]
Howdy! Would you be open to creating a PR to fix this issue? Seems like a fairly straightforward one.

**Comment by AJenbo** [comment]
Sorry, I'm a bit tied up and the projects i work on are all stuck in a pre 8.0 world meaning that I have to do some extra things in order to work on this as it requires 8.0+

**Comment by sawirricardo** [comment]
would love to help 👍. Can I submit one within this week?

**Comment by lukeraymonddowning** [comment]
Thinking on this more, I agree with @a-bashtannik here. Although arguable that it is the one and only solution. However, given that I would like to avoid maintaining multiple environment stub files, I think an error message asking the user to create the file would be the best way forward in my opinion.

**Comment by AJenbo** [comment]
Why not simply create an empty file, Envy is able to populate it after all.

**Comment by a-bashtannik** [comment]
> Why not simply create an empty file, Envy is able to populate it after all.

Just because it's an extra effect without any benefits finally? The abstract idea of this package is a syncing bridge between documentation (`.env.example`) and implementation (`.env`). It can't work without one of the parts, it is senseless even if you create an empty file.

**Comment by a-bashtannik** [comment]
Maybe you are right, and it makes sense to create a `.env.example` file from the existing `.env` source. 

```syntax
if file_exists(".env.example") then 
    main()
else 
    copy(".env", "env.example")
    print(".env.example persisted with .env source")
    main()
end if 
```

**Comment by lukeraymonddowning** [comment]
I think it's dangerous to copy over `.env` directly; there are more than likely confidential details in there and all it takes is one mistake. Let's go with showing a useful error to the user that tells them to create the file first. That way, they have full knowledge of what the problem is and how to resolve it without us getting in their way.
